package test.model;

// Generated 2014-5-26 12:08:17 by Hibernate Tools 3.2.2.GA

/**
 * TblUser generated by hbm2java
 */
public class TblUser implements java.io.Serializable {

	private Integer uuid;
	private int userId;
	private String name;
	private int age;

	public TblUser() {
	}

	public TblUser(int userId, String name, int age) {
		this.userId = userId;
		this.name = name;
		this.age = age;
	}

	public Integer getUuid() {
		return this.uuid;
	}

	public void setUuid(Integer uuid) {
		this.uuid = uuid;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

}
