package test.model;

// Generated 2014-5-26 12:08:17 by Hibernate Tools 3.2.2.GA

/**
 * Test generated by hbm2java
 */
public class Test implements java.io.Serializable {

	private Character a;

	public Test() {
	}

	public Test(Character a) {
		this.a = a;
	}

	public Character getA() {
		return this.a;
	}

	public void setA(Character a) {
		this.a = a;
	}

}
